name: flutter_application_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.1.0
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  dio:
  retrofit: 
  json_annotation: 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  stacked_generator: ^1.0.0
  build_runner: ^2.3.0
  retrofit_generator:
  json_serializable: 
  

flutter:
  uses-material-design: true