# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# platform :ios do
#   desc "Description of what the lane does"
#   lane :custom_lane do
#     # add actions here: https://docs.fastlane.tools/actions
#   end
# end

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Firebase"
  lane :ios_beta_app do
      # match(type: 'adhoc', app_identifier: ['pk.movies.sample'])
      gym(
          project: 'Runner.xcodeproj',
          scheme: 'Release-Development',
          configuration: 'Release-Development',
          clean: true,
          output_directory: 'archives',
          output_name: 'pk.movies.sample.ipa',
          export_method: 'ad-hoc'
      )
      # Upload our build to Firebase
      firebase_app_distribution(
          app: "1:784060653042:ios:a646c336ccae7dde5f5f6b",
          testers:"najia.ikhlaq@gmail.com, najia.ikhlaq@din.global",
          release_notes: "Initial test version of the app",
          firebase_cli_path: "/usr/local/bin/firebase",
          ipa_path: "./build/Runner/Runner.ipa"
      )
  end
end