default_platform(:android)

platform :android do
    desc "<Building app for android>"
    lane :android_beta_app do
        firebase_app_distribution(
            app: "1:784060653042:android:b6e17b297526488e5f5f6b",
            testers: "najia.ikhlaq@gmail.com, najia.ikhlaq@din.global",
            release_notes: "Release notes: this is a sample app test",
            apk_path: "../build/app/outputs/bundle/release/app-release.aab",
            # firebase_cli_token: $FIREBASE_TOKEN,
            service_credentials_file: $FIREBASE_ACCOUNT_SERVICE
        )
    end
end



